# Generated by Django 2.0.1 on 2018-01-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(max_length=255)),
                ('url', models.URLField(max_length=255, null=True)),
                ('file_size', models.SmallIntegerField(null=True)),
                ('point', models.SmallIntegerField(default=0)),
                ('posted_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
